#!/bin/sh

set -e

OUT="../../dist-newstyle"

FAIL="\033[0;31m[FAIL]\033[0m "
SUCC="\033[0;32m[ OK ]\033[0m "

rm -f "$OUT/*.check"

for check in *.check; do
	file=$(basename "$check" .check)

	cat "$file.front" | opteff-exe -b -t direct >"$OUT/$file".check 2>/dev/null
	cmp "$check" "$OUT/$file.check" && printf "$SUCC" || printf "$(diff --color "$check" "$OUT/$file.check")\n$FAIL"
	echo "check cmp on $file"

	for i in $(seq 1 10); do
		cat "$file.front" | opteff-exe -r -t direct >"$OUT/$file".random.check 2>/dev/null
		cmp "$check" "$OUT/$file.random.check" && printf "$SUCC" || printf "$FAIL"
		echo "check random cmp on $file"
	done
done
